---
- name: restart fastd instances
  ansible.builtin.service:
    name: fastd@{{ communities[item.name].shortname }}
    state: restarted
  loop: "{{ serviced_communities }}"

- name: reload nftables
  ansible.builtin.service:
    name: nftables
    state: reloaded
