---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-yaml
        args: [--unsafe]
      - id: check-added-large-files

  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v24.2.0
    hooks:
      - id: ansible-lint
        additional_dependencies:
          - ansible>=2.13.3
          - netaddr
