---
- name: Get os version
  hosts: all

  tasks:
    - name: Get os version
      ansible.builtin.debug:
        msg:
          System {{ inventory_hostname }} is {{ ansible_distribution }} {{
          ansible_distribution_release }} ({{ ansible_kernel }})
