---
- name: Set SELinux mode to permissive
  ansible.posix.selinux:
    state: permissive
    policy: targeted

- name: Ensure kernel-modules-extra is installed (for tcp_westwood)
  ansible.builtin.package:
    name: kernel-modules-extra
    state: latest

- name: Install tcp_westwood modules-load config
  ansible.builtin.copy:
    content: tcp_westwood
    dest: /etc/modules-load.d/tcp_westwood.conf
    mode: "0644"

- name: Install freifunk sysctl config
  ansible.builtin.template:
    src: sysctl-99-freifunk.conf.j2
    dest: /etc/sysctl.d/99-freifunk.conf
    mode: "0644"
  notify:
    - Reload sysctl

- name: Install nf_conntrack module config
  ansible.builtin.copy:
    content: options nf_conntrack hashsize={{ (nf_conntrack_max / 4) | int }}
    dest: /etc/modprobe.d/nf_conntrack.conf
    mode: "0644"
