---
- name: Reload nftables
  ansible.builtin.service:
    name: nftables
    state: reloaded

- name: Restart tunneldigger-broker instances
  ansible.builtin.service:
    name: tunneldigger-broker@{{ item.name }}
    state: restarted
