---
- name: Install git
  ansible.builtin.package:
    name: git
    state: latest

- name: Git checkout mesh-announce
  ansible.builtin.git:
    repo: https://github.com/fflev/mesh-announce.git
    dest: /opt/mesh-announce
    version: "{{ respondd_git_version }}"
  notify:
    - restart respondd

- name: Create configuration
  ansible.builtin.template:
    src: respondd.conf.j2
    dest: /opt/mesh-announce/respondd.conf
    mode: "0644"
    backup: true
  notify:
    - restart respondd

- name: Copy systemd unit0644
  ansible.builtin.copy:
    src: respondd.service
    dest: /etc/systemd/system/respondd.service
    mode: "0644"
  register: respondd_systemd_unit

- name: Enable and start respondd
  ansible.builtin.systemd:
    name: respondd
    state: started
    enabled: true
    daemon_reload: "{{ respondd_systemd_unit.changed }}"

- name: Create firewall rules
  ansible.builtin.copy:
    src: respondd.nft
    dest: /etc/nftables/freifunk/rules.d/10-respondd.nft
    mode: "0644"
  notify:
    - Reload nftables
