---
- name: Create mesh netdevs
  ansible.builtin.template:
    src: mesh-community.netdev.j2
    dest: /etc/systemd/network/mesh-{{ communities[item.name].shortname }}.netdev
    backup: true
    mode: 0644
  loop: "{{ serviced_communities }}"

- name: Create mesh networks
  ansible.builtin.template:
    src: mesh-community.network.j2
    dest: /etc/systemd/network/mesh-{{ communities[item.name].shortname }}.network
    backup: true
    mode: 0644
  loop: "{{ serviced_communities }}"

- name: Create tun networks
  ansible.builtin.template:
    src: tun-community.network.j2
    dest: /etc/systemd/network/tun-{{ communities[item.name].shortname }}.network
    backup: true
    mode: 0644
  loop: "{{ serviced_communities }}"
